In [2]:
import pandas as pd
import numpy as np

In [3]:
titanic = pd.read_csv("../Assignment/Titanic.csv")
tip = pd.read_csv("tip.csv")

print(tip.shape, titanic.shape)

(244, 7) (891, 12)

In [4]:
tip.groupby('day') #returns address only

In [5]:
# how many bills on each day
x = tip.groupby('day').size() # size - is used to count 

# average tip on each day
y = tip.groupby('day')['tip'].mean().round(2) # round(2) - round-off till 2 decimal places
print(x)
print()
print()
print(y)

day
Fri     19
Sat     87
Sun     76
Thur    62
dtype: int64


day
Fri     2.73
Sat     2.99
Sun     3.26
Thur    2.77
Name: tip, dtype: float64

In [6]:
# make a tip_pct column, then average it per day
tip['tip_pct'] = (tip['tip'] / tip['total_bill'] * 100).round(2)
print(tip.head(2))
print(tip.groupby('day')['tip_pct'].mean().round(2))

   total_bill   tip     sex smoker  day    time  size  tip_pct
0       16.99  1.01  Female     No  Sun  Dinner     2     5.94
1       10.34  1.66    Male     No  Sun  Dinner     3    16.05
day
Fri     16.99
Sat     15.31
Sun     16.69
Thur    16.13
Name: tip_pct, dtype: float64

In [ ]:
x = tip.groupby('day').mean(numeric_only=True)['tip']
y = tip.groupby('day')['tip'].mean()
print(x)
print(y)

      total_bill       tip      size    tip_pct
day
Fri    17.151579  2.734737  2.105263  16.991579
Sat    20.441379  2.993103  2.517241  15.314598
Sun    21.410000  3.255132  2.842105  16.689605
Thur   17.682742  2.771452  2.451613  16.126452
day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

In [8]:
tip.head(2)

   total_bill   tip     sex smoker  day    time  size  tip_pct
0       16.99  1.01  Female     No  Sun  Dinner     2     5.94
1       10.34  1.66    Male     No  Sun  Dinner     3    16.05

In [9]:
tip.groupby('size')['tip_pct'].mean().round(1)

size
1    21.7
2    16.6
3    15.2
4    14.6
5    14.2
6    15.6
Name: tip_pct, dtype: float64

In [10]:
tip.groupby('size')['total_bill'].mean().round(2)

size
1     7.24
2    16.45
3    23.28
4    28.61
5    30.07
6    34.83
Name: total_bill, dtype: float64

In [11]:
tip.head(2)

   total_bill   tip     sex smoker  day    time  size  tip_pct
0       16.99  1.01  Female     No  Sun  Dinner     2     5.94
1       10.34  1.66    Male     No  Sun  Dinner     3    16.05

In [12]:
#Q1.1
titanic.groupby('Pclass')['Survived'].mean().round(2) * 100

Pclass
1    63.0
2    47.0
3    24.0
Name: Survived, dtype: float64

In [13]:
titanic.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [14]:
#Q1.2
titanic.groupby('Pclass')['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [15]:
#Q1.3
titanic.groupby('Embarked')['Age'].mean().round(2)

Embarked
C    30.81
Q    28.09
S    29.45
Name: Age, dtype: float64